### PR TITLE
Better wording

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Crauzer — COMMENTED** [review]
Fantome is supposed to be a single tool in the end

**Comment by cloudrex** [comment]
Then why does it say "It offers a variety of tools"?

**Comment by Crauzer** [comment]
The idea is to have tools inside of a tool. The initial thought was that Fantome itself will offer some basic features and it could load any C# WPF tool into itself like a plugin. Thus allowing an easy way for us and others to develop tools.

**Comment by cloudrex** [comment]
Technically that's a collection.

Note that a *collection* is singular.

**Comment by ChewyBomber** [comment]
Big debate right here 😄

**Comment by cloudrex** [comment]
> Fantome is supposed to be a single tool in the end

Just confused on what he meant. At the end, my contribution was very small--does not really add value to the repository.

**Pull request closed without merging**
